#dist: trusty
sudo: required

services:
    - docker

language: go

go:
    - tip

env:
    - GO111MODULE=on

# https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
install: true

script:
    - make test-unit
    # keep environnement variable for sudo
    - docker build -t drand-it . #docker-compose should be self-sufficient, but fails on travis...
    - make test-integration

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker push dedis/drand:latest
    on:
      branch: travis-use-new-deploy
